# Generated by Django 4.1.4 on 2023-03-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholar_name', models.CharField(max_length=500)),
                ('std_1', models.BooleanField()),
                ('std_2', models.BooleanField()),
                ('std_3', models.BooleanField()),
                ('std_4', models.BooleanField()),
                ('std_5', models.BooleanField()),
                ('std_6', models.BooleanField()),
                ('std_7', models.BooleanField()),
                ('std_8', models.BooleanField()),
                ('std_9', models.BooleanField()),
                ('std_10', models.BooleanField()),
                ('std_11', models.BooleanField()),
                ('std_12', models.BooleanField()),
                ('scl_open', models.BooleanField()),
                ('scl_ews', models.BooleanField()),
                ('scl_sebc', models.BooleanField()),
                ('scl_sc_st', models.BooleanField()),
                ('scl_open_pr', models.IntegerField(default=200)),
                ('scl_ews_pr', models.IntegerField(default=200)),
                ('scl_sebc_pr', models.IntegerField(default=200)),
                ('scl_sc_st_pr', models.IntegerField(default=200)),
                ('scl_f_income', models.IntegerField()),
                ('scl_gender_male', models.BooleanField()),
                ('scl_gender_female', models.BooleanField()),
                ('scl_gender_other', models.BooleanField()),
                ('scl_ask_for_pd', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('scl_description', models.TextField()),
            ],
        ),
    ]
