# Generated by Django 4.1.4 on 2023-03-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='scl_ews_pr',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='scl_open_pr',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='scl_sc_st_pr',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='scl_sebc_pr',
            field=models.IntegerField(),
        ),
    ]
