# Generated by Django 4.1.4 on 2023-03-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_school_scl_ews_pr_alter_school_scl_open_pr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholar_name', models.CharField(max_length=200)),
                ('clg_degree_bcom', models.BooleanField()),
                ('clg_degree_bba', models.BooleanField()),
                ('clg_degree_bca', models.BooleanField()),
                ('clg_degree_bsc', models.BooleanField()),
                ('clg_degree_diploma', models.BooleanField()),
                ('clg_degree_btech', models.BooleanField()),
                ('clg_degree_bpharma', models.BooleanField()),
                ('clg_year_1', models.BooleanField()),
                ('clg_year_2', models.BooleanField()),
                ('clg_year_3', models.BooleanField()),
                ('clg_year_4', models.BooleanField()),
                ('clg_year_5', models.BooleanField()),
                ('clg_cat_open', models.BooleanField()),
                ('clg_cat_ews', models.BooleanField()),
                ('clg_cat_sebc', models.BooleanField()),
                ('clg_cat_sc_st', models.BooleanField()),
                ('clg_for_fy_pr_open', models.IntegerField()),
                ('clg_for_fy_pr_ews', models.IntegerField()),
                ('clg_for_fy_pr_sebc', models.IntegerField()),
                ('clg_for_fy_pr_scst', models.IntegerField()),
                ('clg_cgpa_open', models.IntegerField()),
                ('clg_cgpa_ews', models.IntegerField()),
                ('clg_cgpa_sebc', models.IntegerField()),
                ('clg_cgpa_scst', models.IntegerField()),
                ('clg_f_income', models.IntegerField()),
                ('clg_gender_male', models.BooleanField()),
                ('clg_gender_female', models.BooleanField()),
                ('clg_gender_other', models.BooleanField()),
                ('clg_ask_for_pd', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('clg_description', models.TextField()),
            ],
        ),
    ]
