# Generated by Django 4.1.4 on 2023-03-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='clg_ask_for_pd',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='college',
            name='clg_cgpa_ews',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='college',
            name='clg_cgpa_open',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='college',
            name='clg_cgpa_scst',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='college',
            name='clg_cgpa_sebc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='college',
            name='clg_for_fy_pr_ews',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='college',
            name='clg_for_fy_pr_open',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='college',
            name='clg_for_fy_pr_scst',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='college',
            name='clg_for_fy_pr_sebc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='scl_ask_for_pd',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='scl_ews_pr',
            field=models.FloatField(default=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='scl_open_pr',
            field=models.FloatField(default=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='scl_sc_st_pr',
            field=models.FloatField(default=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='scl_sebc_pr',
            field=models.FloatField(default=200),
        ),
    ]
