# Generated by Django 4.1.4 on 2023-03-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_college_clg_ask_for_pd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='scl_pk',
            field=models.IntegerField(default=1),
        ),
    ]
