# Generated by Django 4.1.4 on 2023-03-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_school_scl_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='clg_pk',
            field=models.IntegerField(default=1),
        ),
    ]
