# Generated by Django 4.1.4 on 2023-03-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_college_clg_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='clg_for_fy_pr_scst',
            new_name='clg_for_fy_pr_sc_st',
        ),
    ]
