# Generated by Django 4.1.4 on 2023-03-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_clg_for_fy_pr_scst_college_clg_for_fy_pr_sc_st'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='clg_cgpa_scst',
            new_name='clg_cgpa_sc_st',
        ),
    ]
