# Generated by Django 4.1.4 on 2023-03-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_college_clg_official_link_school_scl_official_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='clg_official_link',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AlterField(
            model_name='school',
            name='scl_official_link',
            field=models.CharField(default='null', max_length=300),
        ),
    ]
