# Generated by Django 4.1.4 on 2023-03-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_college_clg_official_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='clg_note',
            field=models.CharField(default='', max_length=700),
        ),
        migrations.AddField(
            model_name='school',
            name='scl_note',
            field=models.CharField(default='', max_length=700),
        ),
    ]
